/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.reply.storm.dcp

import kotlin.test.Test
import kotlin.test.assertFalse
import kotlin.test.assertTrue

class AppTest {
    @Test fun testContainsSum() {
        // positive
        assertTrue { containsSum(listOf(10, 15, 3, 7), 10) }
        assertTrue { containsSum(listOf(10, 15, 3, 7), 13) }
        assertTrue { containsSum(listOf(10, 15, 3, 7), 17) }
        assertTrue { containsSum(listOf(10, 15, 3, 7), 18) }
        assertTrue { containsSum(listOf(10, 15, 3, 7), 22) }
        assertTrue { containsSum(listOf(10, 15, 3, 7), 25) }
        // negative
        assertFalse { containsSum(listOf(10, 15, 3, 7), 11) }
        assertFalse { containsSum(listOf(10, 15, 3, 7), 12) }
        assertFalse { containsSum(listOf(10, 15, 3, 7), 16) }
        assertFalse { containsSum(listOf(10, 15, 3, 7), 19) }
        assertFalse { containsSum(listOf(10, 15, 3, 7), 23) }
        assertFalse { containsSum(listOf(10, 15, 3, 7), 26) }
    }
}
