/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.reply.storm.dcp

import kotlin.test.Test
import kotlin.test.assertEquals

class Dcp17Test {

    @Test
    fun testStringSmallerThanK() {
        assertEquals("a", Dcp17("a", 2).longestDistinctCharacterSubstring())
    }

    @Test
    fun testStringEqualsK() {
        assertEquals("ab", Dcp17("ab", 2).longestDistinctCharacterSubstring())
    }

    @Test
    fun testLongestDistinctCharacterSubstring() {
        assertEquals("bcb", Dcp17("abcba", 2).longestDistinctCharacterSubstring())
    }
}
