/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.reply.storm.dcp

import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertFalse
import kotlin.test.assertTrue

class Dcp1Test {
    val sample = Dcp1(listOf(10, 15, 3, 7))

    @Test
    fun testContainsSum() {
        // positive
        assertTrue { sample.containsSum(10) }
        assertTrue { sample.containsSum(17) }
        assertTrue { sample.containsSum(18) }
        assertTrue { sample.containsSum(22) }
        assertTrue { sample.containsSum(25) }
        // negative
        assertFalse { sample.containsSum(11) }
        assertFalse { sample.containsSum(12) }
        assertFalse { sample.containsSum(16) }
        assertFalse { sample.containsSum(19) }
        assertFalse { sample.containsSum(23) }
        assertFalse { sample.containsSum(26) }
    }
}
