/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.reply.storm.dcp

import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertFalse
import kotlin.test.assertTrue

class Dcp2Test {
    val sample1 = Dcp2(1, 2, 3, 4, 5)
    val sample2 = Dcp2(3, 2, 1)

    @Test
    fun testProductOfAllOthers() {
        assertEquals(intArrayOf(120, 60, 40, 30, 24).contentToString(), sample1.productOfAllOthers().contentToString())
        assertEquals(intArrayOf(2, 3, 6).contentToString(), sample2.productOfAllOthers().contentToString())
    }

    @Test
    fun testProductOfAllOthersWithoutDivision() {
        assertEquals(intArrayOf(120, 60, 40, 30, 24).contentToString(), sample1.productOfAllOthersWithoutDivision().contentToString())
        assertEquals(intArrayOf(2, 3, 6).contentToString(), sample2.productOfAllOthersWithoutDivision().contentToString())
    }
}
